const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.progressbar,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.progressbar.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.progressbar.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.progressbar.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.progressbar.Acts.SetMaximum,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.CompareOpacity
	];
};
self.C3_JsPropNameTable = [
	{Pin: 0},
	{Photos: 0},
	{Touch: 0},
	{Mouse: 0},
	{Audio: 0},
	{Flash: 0},
	{Finish: 0},
	{Mode1: 0},
	{Mode2: 0},
	{Mode3: 0},
	{Timer: 0},
	{Lev: 0},
	{Level: 0},
	{Text: 0},
	{DEBUG: 0},
	{FinPhoto: 0},
	{FinFlash: 0},
	{LoadScreen: 0},
	{Load: 0},
	{Loading: 0},
	{Family1: 0},
	{Speed: 0},
	{Auto: 0}
];

self.InstanceType = {
	Photos: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Flash: class extends self.ISpriteInstance {},
	Finish: class extends self.ISpriteInstance {},
	Mode1: class extends self.ISpriteInstance {},
	Mode2: class extends self.ISpriteInstance {},
	Mode3: class extends self.ISpriteInstance {},
	Timer: class extends self.IProgressBarInstance {},
	Lev: class extends self.ISpriteInstance {},
	Level: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	DEBUG: class extends self.ISpriteInstance {},
	FinPhoto: class extends self.ISpriteInstance {},
	FinFlash: class extends self.ISpriteInstance {},
	LoadScreen: class extends self.ISpriteInstance {},
	Loading: class extends self.IProgressBarInstance {},
	Family1: class extends self.ISpriteInstance {}
}